server:
  port: 8081

spring:
  application:
    name: snapshot_ui    
  thymeleaf:
    prefix: classpath:/static/html/
    
elasticsearch:
  host: 10.178.221.164
  port: 9200
#  type: 
#    - create_obj
#    - result_obj
#    - delete_obj